[package]
name = "apexkit-core"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
# Custom Crate
apexkit-vector = { path = "../apexkit-vector", default-features = false }
# Database
rusqlite = { version = "0.39.0", features = ["bundled", "hooks", "serde_json", "blob", "session"] }
serde_sqlite_jsonb = "0.2.1" # Zero-copy JSONB wrapper

# Async & Runtime
tokio = { version = "1.37.0", features = ["full"] }
async-trait = "0.1.80"
futures = "0.3"

# Serialization
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.117"

# Utilities
validator = { version = "0.18.1", features = ["derive"] }
thiserror = "1.0.59"
chrono = { version = "0.4", features = ["serde"] }
rand = "0.8.5" # upgrade from 0.8
uuid = { version = "1.8", features = ["v4", "fast-rng"] }
moka = { version = "0.12", features = ["future"] } # Caching

# Logging & Monitoring
tracing = "0.1"

# OpenAPI Documentation
utoipa = "5.4.0"

# Storage & AWS
aws-config = { version = "1.8.12", default-features = false, features = ["behavior-version-latest", "rt-tokio"] }
aws-sdk-s3 = { version = "1.1", default-features = false, features = ["rt-tokio"] }
aws-credential-types = "1.1"
aws-smithy-runtime-api = { version = "1.1", features = ["client"] }
aws-smithy-types = "1.1"
http = "0.2.9" 

# HTTP Clients
reqwest = { version = "0.12", default-features = false, features = ["json", "native-tls-vendored"] }
ureq = { version = "2.9", default-features = false, features = ["tls"] }

rustls = { version = "0.23", default-features = false, features = ["ring", "std", "logging", "tls12"] }

# Email
lettre = { version = "0.11", features = ["tokio1", "smtp-transport", "builder", "tokio1-native-tls", "sendmail-transport"] }

# Auth & Crypto
bcrypt = "0.15"
jsonwebtoken = "9.3.0"
aes-gcm = "0.10"
base64 = "0.21"
secrecy = { version = "0.8", features = ["serde"] }
zeroize = "1.7"

# Search Engine
tantivy = "0.22"

# WASM execution
wasmtime = "24.0.0"
wasmtime-wasi = "24.0.0"

# --- SCRIPTING ENGINE
rquickjs = { version = "0.12.2", features = ["macro", "classes", "futures", "loader"] }
rquickjs-serde = "0.6.1"
# --- ARCHIVE MANAGER ---
zip = { version = "0.6", default-features = false, features = ["deflate"] }
walkdir = "2.4"

# Validation Extensions
regex = "1.10"
url = "2.5"
ring = "0.17.14"

[features]
default = ["onnx"]
onnx = ["apexkit-vector/onnx"]
cuda = ["apexkit-vector/cuda"]
metal = ["apexkit-vector/metal"]