export const QueryEngineDocs = {
  intro:
    'The auto-generated SDK features an advanced SQL Query Engine designed to handle highly complex, multi-field, and aggregate queries. It is fully compatible with the output of the filter UI.',

  flowSnippet: `
/**
 * 1. CAPTURE FILTER VALUES FROM THE FILTER UI (RecordFilters)
 * The Filter UI collects user selections and formats them into a 
 * MongoDB-style query object, then fires 'onApplyFilters(mongoQuery)'.
 */
const mongoQuery = {
  category: "electronics",
  price: { "$gte": 50 },
  status: { "$neq": "archived" }
};

/**
 * 2. FEED THE FILTER VALUES TO THE AUTO-GENERATED SDK
 * pass the filter payload directly into the 'where' field of the 
 * searchRecordsWithSQLQueryEngine query.
 */
const results = await client.collection('products').searchRecordsWithSQLQueryEngine({
  from: "products", 
  select: ["id", "name", "price", "category"], // Optional column projection
  filter: mongoQuery,                          // <--- FED DIRECTLY HERE!
  sort: "-price",                              // Sort descending
  limit: 20,
  offset: 0
});

console.log("Matching Records:", results);
  `,

  advancedSnippets: {
    aggregates: `
// You can also perform SQL aggregations (Sum, Count, Avg) using the same filter:
const metrics = await client.collection('products').searchRecordsWithSQLQueryEngine({
  select: [
    "category",
    { "func": "count", "field": "id", "as": "total_items" },
    { "func": "sum", "field": "price", "as": "category_value" }
  ],
  filter: mongoQuery, // Apply the same user filters to the aggregations!
  group_by: ["category"]
});
    `,
    operators: `
// Supported Filter Operators that can be generated by your inputs:
const query = {
  filter: {
    "price": { "$gt": 100 },                  // Greater than
    "name": { "$contains": "smart" },         // Full-text/Fuzzy contains
    "status": { "$in": ["active", "draft"] }  // In list matches
  }
};
    `,
  },
};
