syntax = "proto3";
package replication;

service Replication {
    rpc SubscribeWal (WalRequest) returns (stream WalFrame);
    rpc ExecuteWrite (WriteRequest) returns (WriteResponse);
    rpc FetchDbSnapshot (SnapshotRequest) returns (stream FileChunk);
    
    // Bi-Directional Stream: Replica sends subscriptions, Master streams CUD events
    rpc StreamEvents (stream EventSubscription) returns (stream DbChangeEvent);
}

message WalRequest { 
    string replica_id = 1; 
    uint64 last_offset = 2; 
    string db_path = 3; 
}

message WalFrame { 
    bytes data = 1; 
    uint64 new_offset = 2; 
    bool is_reset = 3; 
}

message WriteRequest { 
    string sql = 1; 
    bytes params = 2; 
    string db_path = 3; 
}

message WriteResponse { 
    bool success = 1; 
    int64 insert_id = 2; 
    string error = 3; 
}

message SnapshotRequest { 
    string db_path = 1; 
}

message FileChunk { 
    bytes data = 1; 
}

message EventSubscription {
    string replica_id = 1;
    repeated string add_scopes = 2; // e.g., ["root", "tenant:123"]
}

message DbChangeEvent {
    string scope = 1;      // "root", "tenant:123"
    string db_name = 2;    // "data", "core", "system"
    bytes changeset = 3;   // The raw SQLite binary changeset
}